### PR TITLE
chore: create wagmi demo dapp

### PR DESCRIPTION
**Pull request by omridan159**
## Explanation

Create wagmi demo dapp

### `@metamask/package-a`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

### `@metamask/package-b`

- **<CATEGORY>**: Your change here
- **<CATEGORY>**: Your change here

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by abretonc7s — CHANGES_REQUESTED** [review]
Add comments to include Infura project id as well as dapp metadata.

**Review by andreahaku — DISMISSED** [review]
LGTM

**Review by andreahaku — APPROVED** [review]
LGTM

**Review by abretonc7s — APPROVED** [review]

**Review by abretonc7s — CHANGES_REQUESTED** [review]
make sure to validate, I dont know why it needs sdk changes for a wagmi example

**Review by abretonc7s — APPROVED** [review]

**Pull request merged**
