### PR TITLE
Release 70.0.0

### PR DESCRIPTION
**Pull request by abretonc7s**
### Added
- feat: add script to align version before publishing ([#902](https://github.com/MetaMask/metamask-sdk.git/pull/902))
- feat: close modal with error 4001 ([#898](https://github.com/MetaMask/metamask-sdk.git/pull/898))
- feat: emit url event ([#901](https://github.com/MetaMask/metamask-sdk.git/pull/901))
- chore: improve unit tests coverage ([#888](https://github.com/MetaMask/metamask-sdk.git/pull/888))

### Added
- feat: add script to align version before publishing ([#902](https://github.com/MetaMask/metamask-sdk/pull/902))
- feat: update dev rn / expo and empty dappid ([#897](https://github.com/MetaMask/metamask-sdk/pull/897))
- feat: prevent empty dappid ([#891](https://github.com/MetaMask/metamask-sdk/pull/891))
- chore: improve unit tests coverage ([#888](https://github.com/MetaMask/metamask-sdk/pull/888))

### CODE REVIEW

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by christopherferreira9** [comment]
@metamask-bot publish-preview

**Comment by christopherferreira9** [comment]
@metamaskbot publish-preview

**Review by christopherferreira9 — APPROVED** [review]
LGTM

**Pull request merged**
