### PR TITLE
feat: add an e2e test that connect to the test-dapp

### PR DESCRIPTION
**Pull request by omridan159**
Adding an E2E test that connects to the `test-dapp`

### CODE REVIEW

**Review by andreahaku — APPROVED** [review]
LGTM

**Review by christopherferreira9 — CHANGES_REQUESTED** [review]
left down some improvement comments, let me know what you think

**Review by christopherferreira9 — APPROVED** [review]
LGTM

**Review by andreahaku — APPROVED** [review]
LGTM

**Pull request merged**
