### PR TITLE
Release 25.0.0

### PR DESCRIPTION
**Pull request by abretonc7s**
### Added
- fix: commlayer types not fully exported
- feat: refactor MetaMaskSDK class for enhanced modularity and testability  ([#309](https://github.com/MetaMask/metamask-sdk/pull/309))

### Added
- feat: cleanup logs ([#316](https://github.com/MetaMask/metamask-sdk/pull/316))

### Added
- feat: refactor MetaMaskSDK class for enhanced modularity and testability  ([#309](https://github.com/MetaMask/metamask-sdk/pull/309))
- feat: update demo examples ([#316](https://github.com/MetaMask/metamask-sdk/pull/316))

### CODE REVIEW

**Review by christopherferreira9 — APPROVED** [review]
LGTM

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Review by omridan159 — APPROVED** [review]

**Review by omridan159 — DISMISSED** [review]

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Comment by christopherferreira9** [comment]
@metamaskbot publish-preview

**Comment by christopherferreira9** [comment]
LGTM

**Review by christopherferreira9 — APPROVED** [review]
LGTM

**Pull request merged**
