### PR TITLE
Release 31.0.0

### PR DESCRIPTION
**Pull request by abretonc7s**
### Added
- feat: add sdk version and change modal order ([#405](https://github.com/MetaMask/metamask-sdk/pull/405))
- feat: implementing internationalization via i18next package ([#403](https://github.com/MetaMask/metamask-sdk/pull/403))
- feat: alias terminate to disconnect on sdk ([#399](https://github.com/MetaMask/metamask-sdk/pull/399))
- fix typos ([#401](https://github.com/MetaMask/metamask-sdk/pull/401))
- fix: modal cleanup and otp selection ([#402](https://github.com/MetaMask/metamask-sdk/pull/402))

### Added
- fix typos ([#401](https://github.com/MetaMask/metamask-sdk/pull/401))

### Added
- feat: add sdk version and change modal order ([#405](https://github.com/MetaMask/metamask-sdk/pull/405))
- feat: implementing internationalization via i18next package ([#403](https://github.com/MetaMask/metamask-sdk/pull/403))
- fix: modal cleanup and otp selection ([#402](https://github.com/MetaMask/metamask-sdk/pull/402))

### Added
- feat: implementing internationalization via i18next package ([#403](https://github.com/MetaMask/metamask-sdk/pull/403))
- feat: automatically compute account balance and return from sdk-react ([#400](https://github.com/MetaMask/metamask-sdk/pull/400))

### Added
- feat: implementing internationalization via i18next package ([#403](https://github.com/MetaMask/metamask-sdk/pull/403))

### CODE REVIEW

**Review by andreahaku — DISMISSED** [review]
LGTM

**Comment by christopherferreira9** [comment]
QA individual checks:
feat: add sdk version and change modal order (https://github.com/MetaMask/metamask-sdk/pull/405)  ✅

https://github.com/MetaMask/metamask-sdk/assets/104831203/0f781b39-f496-45b6-bdd6-16cbb015dfd1


feat: implementing internationalization via i18next package (https://github.com/MetaMask/metamask-sdk/pull/403) ✅
Screenshot 2023-10-13 at 14 57 15
Screenshot 2023-10-13 at 14 58 12
Screenshot 2023-10-13 at 14 58 37
Screenshot 2023-10-13 at 14 58 51
Screenshot 2023-10-13 at 14 59 05
Screenshot 2023-10-13 at 14 59 17
Screenshot 2023-10-13 at 14 59 42
Screenshot 2023-10-13 at 15 00 02
Screenshot 2023-10-13 at 15 00 18
Screenshot 2023-10-13 at 15 00 32
Screenshot 2023-10-13 at 15 00 47
Screenshot 2023-10-13 at 15 00 59

**Comment by christopherferreira9** [comment]
fix: modal cleanup and otp selection (https://github.com/MetaMask/metamask-sdk/pull/402) ✅
https://github.com/MetaMask/metamask-sdk/assets/104831203/b88cc30f-4abe-4dec-b4e8-efba5af06523

**Comment by christopherferreira9** [comment]
**Dapps checked**
React: ✅
Next: ✅
Node: ✅
Vue: ✅
ReactNative: ✅

**Review by christopherferreira9 — APPROVED** [review]
LGTM

**Pull request merged**
