### PR TITLE
Release 11.0.0

### PR DESCRIPTION
**Pull request by abretonc7s**
### Added
- feat: improved event tracking for extension and inappbrowser ([#200](https://github.com/MetaMask/metamask-sdk/pull/200))
- feat: autoextract favicon on web platforms ([#196](https://github.com/MetaMask/metamask-sdk/pull/196))
- feat: default to enable session persistence ([#197](https://github.com/MetaMask/metamask-sdk/pull/197))
- feat: sdk async init ([#191](https://github.com/MetaMask/metamask-sdk/pull/191))
- feat: switch between extension and mobile provider ([#189](https://github.com/MetaMask/metamask-sdk/pull/189))

### CODE REVIEW

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by deeeed** [comment]
@SocketSecurity ignore tsc@2.0.4

**Pull request merged**
