### PR TITLE
Release 16.0.0

### PR DESCRIPTION
**Pull request by abretonc7s**
### Added
- feat: monorepo examples integration ([#239](https://github.com/MetaMask/metamask-sdk/pull/239))
- fix: sdk hook connector error with strictmode ([#234](https://github.com/MetaMask/metamask-sdk/pull/234))

### Added
- feat: monorepo examples integration ([#239](https://github.com/MetaMask/metamask-sdk/pull/239))
- feat: check init before connect (+dynamic platform import) ([#238](https://github.com/MetaMask/metamask-sdk/pull/238))
- fix: sdk hook connector error with strictmode ([#234](https://github.com/MetaMask/metamask-sdk/pull/234))
- fix: autoconnection setting ([#235](https://github.com/MetaMask/metamask-sdk/pull/235))
- fix: invalid types during build pipeline ([#233](https://github.com/MetaMask/metamask-sdk/pull/233))

### CODE REVIEW

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Review by andreahaku — DISMISSED** [review]
LGTM

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Comment by abretonc7s** [comment]
@metamaskbot publish-preview

**Pull request merged**
