### PR TITLE
Release 32.0.0

### PR DESCRIPTION
**Pull request by abretonc7s**
### Added
- feat: connectAndSign feature ([#410](https://github.com/MetaMask/metamask-sdk/pull/410))

### Added
- feat: connection recovery edge case ([#411](https://github.com/MetaMask/metamask-sdk/pull/411))

### Added
- fix: balance only display when debug is set ([#408](https://github.com/MetaMask/metamask-sdk/pull/408))
- feat: add unit tests to the sdk-react package ([#369](https://github.com/MetaMask/metamask-sdk/pull/369))

### CODE REVIEW

**Review by andreahaku — APPROVED** [review]
LGTM

**Comment by abretonc7s** [comment]
Thanks but issue is on the unit test that wasn't updated. Closing the PR as I update the incorrect unit test separately.

**Comment by abretonc7s** [comment]
> Seems like there's a regression in `@metamask/sdk-communication-layer` introduced in #411:
> 
> ```
> FAIL src/services/SocketService/EventListeners/handleMessage.test.ts
>   ● Console
> 
>     console.warn
>       Invalid key exchange status detected --- updating it.
> 
>       117 |
>       118 |       if (canDecrypt) {
>     > 119 |         console.warn(`Invalid key exchange status detected --- updating it.`);
>           |                 ^
>       120 |         instance.state.keyExchange?.setKeysExchanged(true);
>       121 |       } else {
>       122 |         // received encrypted message before keys were exchanged.
> 
>       at src/services/SocketService/EventListeners/handleMessage.ts:119:17
>       at Object.<anonymous> (src/services/SocketService/EventListeners/handleMessage.test.ts:137:5)
> 
>     console.warn
>       Invalid key exchange status detected --- updating it.
> 
>       117 |
>       118 |       if (canDecrypt) {
>     > 119 |         console.warn(`Invalid key exchange status detected --- updating it.`);
>           |                 ^
>       120 |         instance.state.keyExchange?.setKeysExchanged(true);
>       121 |       } else {
>       122 |         // received encrypted message before keys were exchanged.
> 
>       at src/services/SocketService/EventListeners/handleMessage.ts:119:17
>       at Object.<anonymous> (src/services/SocketService/EventListeners/handleMessage.test.ts:220:5)
> 
>   ● handleMessage › should request a new key exchange if an encrypted message is received before keys are exchanged and not an originator
> 
>     TypeError: _h.setKeysExchanged is not a function
> 
>       118 |       if (canDecrypt) {
>       119 |         console.warn(`Invalid key exchange status detected --- updating it.`);
>     > 120 |         instance.state.keyExchange?.setKeysExchanged(true);
>           |                                     ^
>       121 |       } else {
>       122 |         // received encrypted message before keys were exchanged.
>       123 |         if (instance.state.isOriginator) {
> 
>       at src/services/SocketService/EventListeners/handleMessage.ts:120:37
>       at Object.<anonymous> (src/services/SocketService/EventListeners/handleMessage.test.ts:137:5)
> 
>   ● handleMessage › should start key exchange if an encrypted message is received before keys are exchanged and is an originator
> 
>     TypeError: _h.setKeysExchanged is not a function
> 
>       118 |       if (canDecrypt) {
>       119 |         console.warn(`Invalid key exchange status detected --- updating it.`);
>     > 120 |         instance.state.keyExchange?.setKeysExchanged(true);
>           |                                     ^
>       121 |       } else {
>       122 |         // received encrypted message before keys were exchanged.
>       123 |         if (instance.state.isOriginator) {
> 
>       at src/services/SocketService/EventListeners/handleMessage.ts:120:37
>       at Object.<anonymous> (src/services/SocketService/EventListeners/handleMessage.test.ts:220:5)
> ```
> 
> https://github.com/MetaMask/metamask-sdk/actions/runs/6558478715/job/17812239212?pr=412

Thanks @legobeat , I updated the PR. It was an issue with the unit test not being updated.

**Review by andreahaku — DISMISSED** [review]
LGTM

**Review by christopherferreira9 — APPROVED** [review]
LGTM

**Pull request merged**
